global using LowlandTech.Vylyr.Infrastructure;
global using LowlandTech.Vylyr.Mobile.Services;
global using LowlandTech.Vylyr.Pages;
global using LowlandTech.Vylyr.Services;
global using LowlandTech.Vylyr.ViewModels;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using MudBlazor.Services;
global using System;